import type { Response } from 'express';
import PDFDocument from 'pdfkit';
import { logger } from '../config';

export interface ReportData {
  scanId: string;
  filename: string;
  fileType: string;
  analysisDate: string;
  result: {
    isAuthentic: boolean;
    confidence: number;
    details: any;
  };
}

export async function generatePDFReport(reportData: ReportData, res: Response): Promise<void> {
  try {
    const doc = new PDFDocument({ margin: 50 });
    
    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="SatyaAI-Report-${reportData.scanId}.pdf"`);
    
    // Pipe PDF to response
    doc.pipe(res);
    
    // Header
    doc.fontSize(24).fillColor('#00bfff').text('SatyaAI', { align: 'center' });
    doc.fontSize(18).fillColor('#666').text('Deepfake Detection Report', { align: 'center' });
    doc.moveDown(2);
    
    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#00bfff');
    doc.moveDown();
    
    // Report Details
    doc.fontSize(12).fillColor('#000');
    doc.text(`Report ID: ${reportData.scanId}`, { continued: false });
    doc.text(`Generated: ${new Date().toLocaleString()}`, { continued: false });
    doc.text(`Analysis Date: ${new Date(reportData.analysisDate).toLocaleString()}`, { continued: false });
    doc.moveDown();
    
    // File Information
    doc.fontSize(16).fillColor('#00bfff').text('File Information');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#000');
    doc.text(`Filename: ${reportData.filename}`);
    doc.text(`File Type: ${reportData.fileType.toUpperCase()}`);
    doc.moveDown();
    
    // Analysis Result
    doc.fontSize(16).fillColor('#00bfff').text('Analysis Result');
    doc.moveDown(0.5);
    
    const resultColor = reportData.result.isAuthentic ? '#22c55e' : '#ef4444';
    const resultText = reportData.result.isAuthentic ? 'AUTHENTIC MEDIA' : 'MANIPULATED MEDIA';
    
    doc.fontSize(14).fillColor(resultColor).text(resultText);
    doc.fontSize(12).fillColor('#000').text(`Confidence Score: ${reportData.result.confidence.toFixed(1)}%`);
    doc.moveDown();
    
    // Key Findings
    if (reportData.result.details?.key_findings) {
      doc.fontSize(16).fillColor('#00bfff').text('Key Findings');
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#000');
      
      reportData.result.details.key_findings.forEach((finding: string, index: number) => {
        doc.text(`${index + 1}. ${finding}`, { indent: 20 });
      });
      doc.moveDown();
    }
    
    // Technical Details
    if (reportData.result.details?.metrics) {
      doc.fontSize(16).fillColor('#00bfff').text('Technical Metrics');
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#000');
      
      const metrics = reportData.result.details.metrics;
      if (metrics.faces_detected !== undefined) {
        doc.text(`Faces Detected: ${metrics.faces_detected}`);
      }
      if (metrics.processing_time) {
        doc.text(`Processing Time: ${metrics.processing_time.toFixed(2)}s`);
      }
      doc.moveDown();
    }
    
    // Footer
    doc.fontSize(9).fillColor('#999');
    doc.text('This report was generated by SatyaAI - Advanced Deepfake Detection Platform', 50, 750, {
      align: 'center'
    });
    doc.text('For questions or support, visit: https://satyaai.com', { align: 'center' });
    
    // Finalize PDF
    doc.end();
    
  } catch (error) {
    logger.error('PDF generation error', error as Error);
    // Fallback to JSON if PDF fails
    res.setHeader('Content-Type', 'application/json');
    res.json({
      error: 'PDF generation failed',
      report: reportData
    });
  }
}
